import type { BlogArticle } from './articles';

export const privacyFirstToolsArticles = [
  {
    slug: 'privacy-first-tools',
    path: '/privacy-first-tools',
    publishedAt: '2026-09-20',
    updatedAt: '2026-09-20',
    translations: {
      en: {
        title: 'Privacy-First Online Tools: How ToolGarden Processes Files in Your Browser',
        excerpt: 'See how ToolGarden uses fflate, Canvas, Web APIs, browser JavaScript, WebAssembly, and local models to process everyday files without uploading tool input to a server.',
        metaTitle: 'Privacy-First Online Tools: Browser-Local Processing',
        metaDescription: 'Learn how ToolGarden privacy-first tools process ZIP, images, JSON, Base64, PDFs, audio, and other files locally with browser APIs, JavaScript, WASM, and fflate.',
        readingTime: '9 min read',
        tags: ['privacy-first tools', 'browser-local processing', 'no upload', 'Web APIs', 'fflate'],
        relatedTools: [
          { label: 'ZIP Compressor', href: '/zip-compress', description: 'Create ZIP archives locally with fflate.' },
          { label: 'Image Tools', href: '/image', description: 'Edit, compress, convert, and inspect images with Canvas and browser APIs.' },
          { label: 'JSON Tools', href: '/json-tools', description: 'Format, validate, compare, and convert JSON in browser JavaScript.' },
          { label: 'Image to Base64', href: '/image/to-base64', description: 'Encode images as Base64 with browser-native APIs.' },
        ],
        blocks: [
          { type: 'lead', text: 'Privacy-first is not a badge added to ToolGarden after the tools were built. It is the default data path: when a browser can perform a task well, the text or file stays on the user’s device and the browser creates the result.' },
          { type: 'paragraph', text: 'That matters for ordinary work. JSON can contain customer records, screenshots can reveal internal dashboards, ZIP archives can hold source code, and PDFs can contain contracts or identity documents. Uploading those files to an unknown conversion server creates a copy and a trust decision that many small tasks do not need.' },
          { type: 'quote', text: 'The website delivers the application. Your browser performs the transformation. Tool input is not sent to a processing API.' },
          { type: 'heading', level: 2, text: 'What “privacy-first” means here' },
          { type: 'paragraph', text: 'ToolGarden separates the page-delivery data flow from the tool-input data flow. The site still loads HTML, JavaScript, CSS, fonts, WebAssembly modules, workers, and sometimes model files. Page-level analytics or advertising may also make their own documented requests. Those requests are not the same as uploading the JSON, image, archive, document, or media file selected inside a tool.' },
          { type: 'paragraph', text: 'For supported workflows, the selected input remains in browser memory or browser-managed local storage while JavaScript and Web APIs process it. The result is exposed as text, a preview, a Blob, or a local download. ToolGarden does not need a server-side job queue, temporary upload bucket, conversion log, or retention policy for that input because it never receives it.' },
          { type: 'heading', level: 2, text: 'The four promises shown on every tool' },
          { type: 'list', items: [
            '✓ Runs locally in your browser',
            '✓ Your files are not uploaded',
            '✓ No server-side processing',
            '✓ No account required',
          ] },
          { type: 'paragraph', text: 'These statements appear on every tool page as a concise summary of the processing boundary. The tool-specific article below each workspace explains the actual input API, parser or library, output method, supported formats, and limits, so the privacy claim can be checked against a concrete implementation rather than treated as a generic slogan.' },
          { type: 'heading', level: 2, text: 'How each tool category works' },
          { type: 'table', headers: ['Input', 'Local implementation', 'What stays on your device'], rows: [
            ['ZIP archives', 'fflate reads, compresses, and extracts archive entries in browser JavaScript.', 'Filenames and file contents'],
            ['Images', 'File, Blob, ImageBitmap, Canvas, OffscreenCanvas, Web Workers, WebCodecs where available, and local WASM codecs.', 'Source pixels, previews, edits, and exports'],
            ['JSON and structured text', 'Browser JavaScript plus pure parsers and converters for formatting, validation, repair, diffing, JSONPath, YAML, XML, and CSV.', 'Pasted payloads, configuration, logs, and results'],
            ['Base64 and text encodings', 'TextEncoder, TextDecoder, Blob, FileReader, browser Base64 primitives, and Web Crypto where hashing or cryptography is required.', 'Plaintext, encoded values, and selected files'],
            ['PDF and documents', 'pdf-lib, PDF.js, Canvas, fflate, and format-specific browser libraries handle supported merge, split, render, extract, and export workflows.', 'Document bytes and rendered pages'],
            ['Audio and video', 'Web Audio, media elements, Workers, FFmpeg WebAssembly, and local speech or separation models where supported.', 'Media samples and generated output'],
            ['Local AI tools', 'ONNX Runtime Web, Transformers.js, WebAssembly or WebGPU, and downloaded model assets run inference on the device.', 'Images, audio, intermediate tensors, and results'],
          ] },
          { type: 'heading', level: 2, text: 'ZIP files: fflate instead of an upload service' },
          { type: 'paragraph', text: 'ZIP compression and extraction use fflate, a compact JavaScript compression library. The browser reads each selected File, creates or parses archive entries, and returns a Blob for download. Because archive filenames and contents are handled in the tab, a source-code bundle, document folder, or photo collection does not need to pass through a remote decompression endpoint.' },
          { type: 'paragraph', text: 'The tradeoff is memory. Browser tabs have finite memory, and archive operations may temporarily hold input, decompressed data, and output at the same time. Very large archives, encrypted formats, damaged ZIP files, or unusual compression methods may be better handled by trusted desktop software.' },
          { type: 'callout', title: 'Related: building browser-local ZIP tools', text: 'This engineering guide covers File and ArrayBuffer input, fflate zipSync and unzipSync, compression levels, legacy filenames, Blob downloads, and ZIP security limits.', href: '/blog/how-to-build-online-file-compress-and-extract', linkLabel: 'Read the ZIP implementation guide' },
          { type: 'heading', level: 2, text: 'Images: Canvas, Web APIs, Workers, and local codecs' },
          { type: 'paragraph', text: 'Image tools decode files with browser APIs, draw pixels to Canvas or OffscreenCanvas, apply transforms, and export a new Blob. Workers keep expensive operations away from the interface. When the browser cannot natively encode a target format, a local WebAssembly codec can provide that capability without sending the image away.' },
          { type: 'paragraph', text: 'Canvas export commonly removes EXIF metadata. That can reduce accidental location leakage, but it can also remove copyright or workflow metadata. Users should inspect the output when metadata matters, and keep an untouched original until the result has been verified.' },
          { type: 'callout', title: 'Related: client-side image processing', text: 'Learn how Canvas, ImageBitmap, OffscreenCanvas, Workers, codecs, memory management, and output checks fit together in production image tools.', href: '/blog/developer-client-side-image-processing', linkLabel: 'Read the image processing guide' },
          { type: 'heading', level: 2, text: 'JSON: ordinary browser JavaScript, deliberately kept local' },
          { type: 'paragraph', text: 'JSON formatting does not require a cloud service. ToolGarden uses JavaScript parsers and pure utility functions for formatting, minifying, repairing, validating, comparing, querying, and converting structured data. React pages manage input and presentation; parsing and conversion live in reusable utilities that return explicit success or error outcomes.' },
          { type: 'paragraph', text: 'This is especially useful for API responses, configuration files, logs, and JWT payloads. Local processing removes an unnecessary network hop, but users should still redact secrets before sharing the output and remember that decoding a token is not the same as decrypting it.' },
          { type: 'callout', title: 'Related: the complete browser-local processing guide', text: 'The pillar guide explains no-upload architecture, browser storage, offline behavior, verification steps, and the limits of local processing.', href: '/blog/complete-guide-browser-local-data-processing', linkLabel: 'Read the browser-local guide' },
          { type: 'heading', level: 2, text: 'Base64: encoding is local, but it is not encryption' },
          { type: 'paragraph', text: 'TextEncoder and TextDecoder convert Unicode text to bytes and back. Blob, FileReader, and browser Base64 primitives handle files and data URLs. These operations are deterministic and can run entirely in the tab. No remote encoder is needed.' },
          { type: 'paragraph', text: 'Base64 only changes representation. Anyone with the encoded value can normally decode it, so it must not be presented as a privacy or security control. When confidentiality is required, use appropriate encryption and key management rather than an encoding tool.' },
          { type: 'callout', title: 'Related: Base64 encoding explained', text: 'See how text, bytes, Base64, Base64URL, Data URLs, Unicode, and common encoding mistakes differ.', href: '/blog/base64-encoding-explained-common-pitfalls', linkLabel: 'Read the Base64 guide' },
          { type: 'heading', level: 2, text: 'PDFs and documents: parse, render, transform, and package locally' },
          { type: 'paragraph', text: 'PDF tools read selected files through the File API. PDF.js parses and renders pages; pdf-lib handles operations such as merge, split, extraction, organization, watermarking, and encryption; Canvas creates page images and previews. Office formats are ZIP-based packages, so supported document workflows can use fflate together with XML and format-specific libraries before returning a PDF, DOCX, or other Blob.' },
          { type: 'paragraph', text: 'The input bytes, page content, rendered canvases, and generated document remain in the tab. Complex Office layouts, signatures, forms, annotations, accessibility structure, and archival requirements still need careful output review.' },
          { type: 'callout', title: 'Related: local PDF tools', text: 'This practical guide covers browser-local PDF workflows, page operations, text extraction, privacy checks, and the cases where desktop software is a better fit.', href: '/blog/pdf-tools-guide', linkLabel: 'Read the PDF tools guide' },
          { type: 'heading', level: 2, text: 'Audio and video: Web Audio and FFmpeg WebAssembly' },
          { type: 'paragraph', text: 'Media tools use File and Blob URLs for local playback, Web Audio for decoding and signal operations, and FFmpeg WebAssembly for supported conversion, trimming, extraction, or compression tasks. Speech recognition and stem separation use model assets downloaded to the browser, while the selected recording or media file stays on the device during inference.' },
          { type: 'paragraph', text: 'Large media files consume substantial memory and CPU. The first model or FFmpeg load can also be large, so the page makes progress and browser limits visible instead of quietly switching to a remote processing job.' },
          { type: 'callout', title: 'Related: browser-local audio separation', text: 'Explore how model loading, Web Workers, Web Audio, local inference, progress reporting, and memory limits work in an on-device audio tool.', href: '/blog/split-song-into-vocals-instrumental-stems-browser', linkLabel: 'Read the local audio guide' },
          { type: 'heading', level: 2, text: 'Text, QR codes, and file merging: deterministic browser libraries' },
          { type: 'paragraph', text: 'Text counters, diff tools, Markdown conversion, subtitle parsing, URL building, timestamps, UUIDs, color conversion, and QR generation operate on strings or typed arrays in JavaScript. File-merging tools read each input with the File API, combine rows, pages, slides, XML parts, images, or text according to the format, then create a downloadable Blob. No account or server job is required for these deterministic transformations.' },
          { type: 'paragraph', text: 'Each tool page documents its own parser and output constraints. A CSV merge has different correctness risks from a DOCX package merge, even though both share the same local-only data path.' },
          { type: 'heading', level: 2, text: 'Heavy tasks: WebAssembly, Workers, and on-device models' },
          { type: 'paragraph', text: 'Some jobs need more than built-in browser functions. PDF parsing, AVIF encoding, audio conversion, speech recognition, background removal, and similar features can use WebAssembly, Web Workers, WebGPU, or local machine-learning models. The browser may download a runtime or model on first use, then applies it to the user’s data locally.' },
          { type: 'paragraph', text: 'A model download is network activity, but it should contain application assets rather than the user’s input. ToolGarden treats that distinction as part of the product contract and documents cases where browser support, memory, file size, or model quality limits the workflow.' },
          { type: 'callout', title: 'Related: privacy risks in online converters', text: 'Use this checklist to evaluate upload-based converters, retention claims, unnecessary copies, redaction, sharing, and safer local alternatives.', href: '/blog/privacy-risks-online-file-converters', linkLabel: 'Read the converter privacy checklist' },
          { type: 'heading', level: 2, text: 'How to verify a no-upload claim' },
          { type: 'list', ordered: true, items: [
            'Use a harmless sample file rather than sensitive production data.',
            'Open the browser developer tools and select the Network panel.',
            'Clear existing requests, run the tool, and inspect new POST, PUT, WebSocket, or unusually large requests.',
            'Distinguish application assets such as scripts, WASM, workers, and model files from request bodies containing your sample.',
            'Repeat the check after major product changes or when using a tool with a different processing model.',
          ] },
          { type: 'heading', level: 2, text: 'Limits and honest exceptions' },
          { type: 'paragraph', text: 'Browser-local processing reduces exposure; it does not make every workflow automatically secure. The correct domain, HTTPS delivery, browser extensions, device security, downloaded output, clipboard history, and local backups still matter. Highly regulated or extremely sensitive material may require an approved offline environment even when a web tool makes no upload.' },
          { type: 'list', items: [
            'Large files can exceed browser memory or take longer than desktop software.',
            'Specialized or encrypted formats may be unsupported.',
            'Complex document layouts and color workflows can lose fidelity.',
            'First use may require downloading a codec, runtime, or model.',
            'Analytics and advertising are separate site data flows described in the privacy policy.',
          ] },
          { type: 'callout', title: 'Read the full privacy policy', text: 'The privacy policy explains site analytics, advertising, local storage, third-party resources, and the boundary between page requests and tool-input processing.', href: '/privacy', linkLabel: 'Open the privacy policy' },
          { type: 'heading', level: 2, text: 'The policy in one sentence' },
          { type: 'paragraph', text: 'If a useful transformation can run reliably in the browser, ToolGarden keeps it there, explains the technology and limits, and avoids creating a server-side copy of the user’s input.' },
        ],
        faq: [
          { question: 'Does ToolGarden upload files selected in a tool?', answer: 'Supported tools are designed to process selected files and pasted text in the browser, without sending that input to a processing API. The page still downloads normal application assets, and analytics or advertising may make separate requests described in the privacy policy.' },
          { question: 'Can a browser-local tool work offline?', answer: 'Some tools can continue working after the required page, scripts, codecs, and models have been cached, but offline behavior varies by browser and feature. A first visit may require network access to download application assets.' },
          { question: 'Is Base64 encryption?', answer: 'No. Base64 is a reversible encoding format. It does not provide confidentiality, authentication, or access control.' },
          { question: 'Is local processing always safer than desktop software?', answer: 'Not automatically. It avoids an upload and server-side copy, but browser, device, extension, and output handling risks remain. Approved desktop or offline systems may be more appropriate for regulated or exceptionally sensitive data.' },
        ],
      },
      zh: {
        title: '隐私优先的在线工具：ToolGarden 如何在浏览器本地处理文件',
        excerpt: '了解 ToolGarden 如何使用 fflate、Canvas、Web API、浏览器 JavaScript、WebAssembly 与本地模型处理日常文件，同时避免把工具输入上传到服务器。',
        metaTitle: '隐私优先的在线工具：浏览器本地处理原理',
        metaDescription: '介绍 ToolGarden 隐私优先策略：ZIP、图片、JSON、Base64、PDF、音视频如何通过 fflate、Canvas、Web API、JavaScript 与 WASM 在浏览器本地处理。',
        readingTime: '约 9 分钟阅读',
        tags: ['隐私优先工具', '浏览器本地处理', '文件不上传', 'Web API', 'fflate'],
        relatedTools: [
          { label: 'ZIP 压缩', href: '/zip-compress', description: '使用 fflate 在浏览器本地创建 ZIP 压缩包。' },
          { label: '图片工具', href: '/image', description: '通过 Canvas 与浏览器 API 编辑、压缩、转换和检查图片。' },
          { label: 'JSON 工具', href: '/json-tools', description: '用浏览器 JavaScript 格式化、校验、对比和转换 JSON。' },
          { label: '图片转 Base64', href: '/image/to-base64', description: '使用浏览器原生 API 把图片编码为 Base64。' },
        ],
        blocks: [
          { type: 'lead', text: '“隐私优先”不是 ToolGarden 做完工具后再贴上的标签，而是默认的数据路径：只要浏览器能够可靠地完成任务，文本或文件就留在用户设备上，由浏览器直接生成结果。' },
          { type: 'paragraph', text: '这对日常工作很重要。JSON 可能包含客户记录，截图可能暴露内部后台，ZIP 可能装着源代码，PDF 可能是合同或身份证明。把这些文件上传到未知的转换服务器，会额外产生一份副本和一次信任决策，而许多小任务根本不需要付出这个代价。' },
          { type: 'quote', text: '网站负责交付应用，浏览器负责执行转换；工具里的输入不会被发送到处理 API。' },
          { type: 'heading', level: 2, text: '这里的“隐私优先”具体指什么' },
          { type: 'paragraph', text: 'ToolGarden 把“页面资源请求”和“工具输入处理”视为两条不同的数据流。网站仍然需要加载 HTML、JavaScript、CSS、字体、WebAssembly、Worker，有些功能还会下载模型文件；页面统计或广告也可能发出各自已披露的请求。但这些请求不等于上传你在工具中选择的 JSON、图片、压缩包、文档或媒体文件。' },
          { type: 'paragraph', text: '在受支持的流程中，输入保留在浏览器内存或浏览器管理的本地存储中，由 JavaScript 与 Web API 处理，结果以文本、预览、Blob 或本地下载的形式交还。服务器不接收输入，因此也不需要为这些输入建立任务队列、临时存储桶、转换日志或保留期限。' },
          { type: 'heading', level: 2, text: '每个工具页都会显示的四项承诺' },
          { type: 'list', items: [
            '✓ 在你的浏览器本地运行',
            '✓ 你的文件不会上传',
            '✓ 不经过服务器处理',
            '✓ 无需注册账号',
          ] },
          { type: 'paragraph', text: '这四句话会显示在每个工具页上，用来概括处理边界。每个工作区下方的工具正文还会继续说明实际使用的输入 API、解析器或依赖库、输出方式、支持格式与限制，让隐私声明能够对应到具体实现，而不是停留在通用口号。' },
          { type: 'heading', level: 2, text: '不同工具是怎样在本地实现的' },
          { type: 'table', headers: ['输入类型', '本地实现', '留在设备上的内容'], rows: [
            ['ZIP 压缩包', 'fflate 在浏览器 JavaScript 中读取、压缩和解压条目。', '文件名与文件内容'],
            ['图片', 'File、Blob、ImageBitmap、Canvas、OffscreenCanvas、Web Worker、可用时的 WebCodecs，以及本地 WASM 编解码器。', '原图像素、预览、编辑过程和导出结果'],
            ['JSON 与结构化文本', '浏览器 JavaScript 配合纯函数解析器，完成格式化、校验、修复、Diff、JSONPath，以及 YAML、XML、CSV 转换。', '粘贴的数据、配置、日志和结果'],
            ['Base64 与文本编码', 'TextEncoder、TextDecoder、Blob、FileReader、浏览器 Base64 能力；哈希或加密场景使用 Web Crypto。', '原文、编码值和所选文件'],
            ['PDF 与文档', 'pdf-lib、PDF.js、Canvas、fflate 与格式专用浏览器库完成受支持的合并、拆分、渲染、提取与导出。', '文档字节与渲染页面'],
            ['音频与视频', 'Web Audio、媒体元素、Worker、FFmpeg WebAssembly，以及受支持的本地语音或分离模型。', '媒体采样和生成结果'],
            ['本地 AI 工具', 'ONNX Runtime Web、Transformers.js、WebAssembly 或 WebGPU 配合下载到设备的模型运行推理。', '图片、音频、中间张量和结果'],
          ] },
          { type: 'heading', level: 2, text: 'ZIP：使用 fflate，而不是上传解压服务' },
          { type: 'paragraph', text: 'ZIP 压缩和解压使用轻量 JavaScript 压缩库 fflate。浏览器读取每个 File，创建或解析压缩包条目，最后生成 Blob 供用户下载。文件名和内容都在当前标签页中处理，源代码包、资料文件夹或照片集合无需经过远程解压接口。' },
          { type: 'paragraph', text: '代价是内存占用。浏览器标签页的内存有限，压缩操作可能同时保留输入、解压数据和输出。超大压缩包、加密格式、损坏文件或少见压缩算法，更适合交给可信的桌面软件。' },
          { type: 'callout', title: '相关文章：浏览器本地 ZIP 工具实现', text: '这篇工程指南详细介绍 File 与 ArrayBuffer 输入、fflate 的 zipSync 和 unzipSync、压缩等级、旧编码文件名、Blob 下载与 ZIP 安全边界。', href: '/blog/how-to-build-online-file-compress-and-extract', linkLabel: '阅读 ZIP 实现指南' },
          { type: 'heading', level: 2, text: '图片：Canvas、Web API、Worker 与本地编解码器' },
          { type: 'paragraph', text: '图片工具通过浏览器 API 解码文件，把像素绘制到 Canvas 或 OffscreenCanvas，执行变换后导出新的 Blob。Worker 可以把耗时操作移出界面线程；如果浏览器不能原生编码目标格式，本地 WebAssembly 编解码器可以补足能力，而不必把图片发往服务器。' },
          { type: 'paragraph', text: 'Canvas 重新导出通常会移除大部分 EXIF 信息，这有助于减少 GPS 位置泄露，但也可能清除版权或工作流元数据。元数据重要时应检查输出，并在确认结果前保留未修改的原文件。' },
          { type: 'callout', title: '相关文章：客户端图片处理', text: '了解 Canvas、ImageBitmap、OffscreenCanvas、Worker、编解码器、内存管理与输出检查如何组成可用于生产环境的图片工具。', href: '/blog/developer-client-side-image-processing', linkLabel: '阅读图片处理指南' },
          { type: 'heading', level: 2, text: 'JSON：刻意保持本地的浏览器 JavaScript' },
          { type: 'paragraph', text: 'JSON 格式化不需要云服务。ToolGarden 使用 JavaScript 解析器和纯函数工具完成格式化、压缩、修复、校验、对比、查询与结构化数据转换。React 页面只管理输入和展示；解析与转换逻辑位于可复用工具层，并返回明确的成功或错误结果。' },
          { type: 'paragraph', text: '这对 API 响应、配置文件、日志和 JWT 载荷尤其有用。本地处理消除了一次不必要的网络传输，但分享结果前仍应移除密钥等敏感信息，同时记住“解码令牌”不等于“解密令牌”。' },
          { type: 'callout', title: '相关文章：浏览器本地处理完整指南', text: '支柱指南系统说明不上传架构、浏览器存储、离线行为、验证步骤和本地处理能力边界。', href: '/blog/complete-guide-browser-local-data-processing', linkLabel: '阅读浏览器本地处理指南' },
          { type: 'heading', level: 2, text: 'Base64：本地编码，但不是加密' },
          { type: 'paragraph', text: 'TextEncoder 和 TextDecoder 负责 Unicode 文本与字节之间的转换，Blob、FileReader 与浏览器 Base64 能力处理文件和 Data URL。这些操作是确定性的，可以完全在标签页内完成，不需要远程编码器。' },
          { type: 'paragraph', text: 'Base64 只改变数据表示形式。拿到编码值的人通常都能还原内容，因此它不能被当作隐私或安全措施。需要保密时，应使用合适的加密与密钥管理，而不是编码工具。' },
          { type: 'callout', title: '相关文章：Base64 编码详解', text: '了解文本、字节、Base64、Base64URL、Data URL、Unicode 之间的区别，以及常见编码错误。', href: '/blog/base64-encoding-explained-common-pitfalls', linkLabel: '阅读 Base64 指南' },
          { type: 'heading', level: 2, text: 'PDF 与文档：在本地解析、渲染、转换和打包' },
          { type: 'paragraph', text: 'PDF 工具通过 File API 读取所选文件。PDF.js 负责解析和渲染页面；pdf-lib 处理合并、拆分、页面提取、排序、水印和加密等操作；Canvas 用于生成页面图片和预览。Office 格式本质上是 ZIP 包，因此受支持的文档流程可以使用 fflate 配合 XML 与格式专用库处理，最后返回 PDF、DOCX 或其他 Blob。' },
          { type: 'paragraph', text: '输入字节、页面内容、渲染 Canvas 与生成文档都保留在标签页中。复杂 Office 排版、签名、表单、批注、无障碍结构与归档要求仍需要仔细检查输出。' },
          { type: 'callout', title: '相关文章：浏览器本地 PDF 工具', text: '这篇实用指南介绍 PDF 页面操作、文本提取、隐私检查，以及更适合使用桌面软件的场景。', href: '/blog/pdf-tools-guide', linkLabel: '阅读 PDF 工具指南' },
          { type: 'heading', level: 2, text: '音频与视频：Web Audio 和 FFmpeg WebAssembly' },
          { type: 'paragraph', text: '媒体工具使用 File 与 Blob URL 在本地播放，通过 Web Audio 解码并执行信号处理，再用 FFmpeg WebAssembly 完成受支持的转换、剪辑、提取或压缩任务。语音识别和音轨分离会把模型资源下载到浏览器，而所选录音或媒体文件在推理期间仍留在设备上。' },
          { type: 'paragraph', text: '大型媒体文件会占用较多内存与 CPU，模型或 FFmpeg 首次加载体积也可能较大。因此页面会显示进度和浏览器限制，而不会静默切换到远程处理任务。' },
          { type: 'callout', title: '相关文章：浏览器本地音轨分离', text: '了解模型加载、Web Worker、Web Audio、本地推理、进度报告与内存限制如何组成设备端音频工具。', href: '/blog/split-song-into-vocals-instrumental-stems-browser', linkLabel: '阅读本地音频指南' },
          { type: 'heading', level: 2, text: '文本、二维码与文件合并：确定性的浏览器工具库' },
          { type: 'paragraph', text: '字数统计、文本 Diff、Markdown 转换、字幕解析、URL 构建、时间戳、UUID、颜色转换与二维码生成，都通过 JavaScript 处理字符串或类型化数组。文件合并工具使用 File API 读取每个输入，按格式组合行、页面、幻灯片、XML 部件、图片或文本，最后创建可下载 Blob，不需要账号或服务器任务。' },
          { type: 'paragraph', text: '每个工具页都会说明自己的解析器和输出限制。CSV 合并与 DOCX 包合并虽然共享同一条本地数据路径，但正确性风险并不相同。' },
          { type: 'heading', level: 2, text: '重型任务：WebAssembly、Worker 与设备端模型' },
          { type: 'paragraph', text: '有些任务超出浏览器内置能力。PDF 解析、AVIF 编码、音频转换、语音识别、图片去背景等功能，可以使用 WebAssembly、Web Worker、WebGPU 或本地机器学习模型。首次使用时浏览器可能下载运行时或模型，随后在设备上处理用户数据。' },
          { type: 'paragraph', text: '模型下载属于网络活动，但其中应当是应用资源，而不是用户输入。ToolGarden 把这一区别视为产品契约的一部分，并明确说明浏览器兼容性、内存、文件大小和模型质量带来的限制。' },
          { type: 'callout', title: '相关文章：在线转换工具的隐私风险', text: '使用这份清单评估上传式转换器、数据保留声明、不必要副本、脱敏、分享方式与更安全的本地替代方案。', href: '/blog/privacy-risks-online-file-converters', linkLabel: '阅读转换工具隐私清单' },
          { type: 'heading', level: 2, text: '怎样验证“不上传”声明' },
          { type: 'list', ordered: true, items: [
            '使用无敏感信息的测试文件，不要直接拿生产数据验证。',
            '打开浏览器开发者工具，进入 Network（网络）面板。',
            '清空已有请求，运行工具，检查新出现的 POST、PUT、WebSocket 或体积异常的请求。',
            '区分脚本、WASM、Worker、模型等应用资源，与包含测试文件内容的请求体。',
            '产品发生较大更新，或切换到处理模式不同的工具时，重新检查一次。',
          ] },
          { type: 'heading', level: 2, text: '限制与诚实的边界' },
          { type: 'paragraph', text: '浏览器本地处理降低了暴露面，但不会让所有流程自动安全。正确域名、HTTPS、浏览器扩展、设备安全、下载结果、剪贴板历史和本地备份仍然重要。即使网页工具不上传数据，受严格监管或极高敏感度的材料仍可能必须在获批的离线环境中处理。' },
          { type: 'list', items: [
            '大文件可能超出浏览器内存，速度也可能慢于桌面软件。',
            '特殊格式或加密格式可能不受支持。',
            '复杂文档排版和色彩工作流可能损失保真度。',
            '首次使用可能需要下载编解码器、运行时或模型。',
            '统计与广告属于独立的网站数据流，具体说明见隐私政策。',
          ] },
          { type: 'callout', title: '阅读完整隐私政策', text: '隐私政策说明页面统计、广告、本地存储、第三方资源，以及页面请求和工具输入处理之间的边界。', href: '/privacy', linkLabel: '打开隐私政策' },
          { type: 'heading', level: 2, text: '一句话总结这项策略' },
          { type: 'paragraph', text: '只要某项实用转换能够在浏览器中可靠运行，ToolGarden 就把它留在浏览器里，说明所用技术和能力边界，并避免在服务器端创建用户输入的副本。' },
        ],
        faq: [
          { question: 'ToolGarden 会上传工具中选择的文件吗？', answer: '受支持的工具会在浏览器中处理所选文件和粘贴文本，不把这些输入发送到处理 API。页面仍会下载正常的应用资源；统计或广告可能产生隐私政策中说明的独立请求。' },
          { question: '浏览器本地工具可以离线使用吗？', answer: '所需页面、脚本、编解码器和模型缓存后，部分工具可以继续工作，但离线能力取决于浏览器与具体功能。首次访问通常仍需要联网下载应用资源。' },
          { question: 'Base64 是加密吗？', answer: '不是。Base64 是可逆的编码格式，不提供保密性、身份验证或访问控制。' },
          { question: '本地处理一定比桌面软件安全吗？', answer: '不一定。它避免了上传和服务器副本，但浏览器、设备、扩展与输出处理风险仍然存在。对于受监管或特别敏感的数据，获批的桌面或离线系统可能更合适。' },
        ],
      },
    },
  },
] satisfies BlogArticle[];
