import { defineToolContent } from './define';

export const audioBitrateContent = defineToolContent({
  zh: {
    overview: ['音频比特率表示编码后每秒使用的数据量。对 MP3 等有损格式，较高比特率通常能保留更多细节但生成更大文件；实际质量还取决于编码器、声道、内容复杂度和源文件。', '调整比特率需要重新编码，不能把低比特率来源变成高保真音频。此工具适合为了平台限制、下载速度或存储预算生成新的交付版本，同时保留原始母版。'],
    steps: [['确认来源与限制', '记录原文件参数和目标平台的最大体积或推荐比特率。'], ['选择目标数值', '语音可测试较低值，复杂音乐应保守降低。'], ['试听并计算体积', '比较关键段落和下载大小，选择满足质量底线的版本。']],
    scenarios: [['统一发布参数', '把多条语音输出为同一比特率，便于平台处理和预估体积。'], ['降低移动端传输', '生成较小副本供网络受限环境播放。'], ["满足平台的上传规格", "部分播客平台和内容系统对码率有明确要求，需要把文件重新编码到指定数值才能通过校验。"]],
    notes: ['把 64 kbps 文件转成 320 kbps 只会增大文件，不会恢复细节。', '同一数值在不同编码格式之间不能直接代表相同质量。', '固定比特率便于估算体积，但内容感知编码在不同段落的效率可能不同。'],
    specs: [["可选档位", "常用 96 / 128 / 192 / 256 / 320 kbps，按目标系统要求指定"], ["编码模式", "定码率（CBR），每秒数据量固定，便于预估体积和满足上传限制"], ["提高比特率", "不会提升音质，只会增大体积：源里没有的信息补不回来"], ["时长与声道", "保持不变，只改变每秒的数据量"], ["体积计算", "体积 ≈ 比特率 ÷ 8 × 秒数，可据此反推能满足限制的档位"], ["处理位置", "浏览器内的 FFmpeg WebAssembly，音频文件不上传"]],
    faq: [{ question: "把 128 kbps 调到 320 kbps 有意义吗？", answer: "只有在下游系统硬性要求 320 kbps 时才有意义。音质不会提升：源文件里已经丢掉的高频不会因为分配了更多比特而回来，你只是得到一个更大的文件。" }, { question: "CBR 和 VBR 该选哪个？", answer: "这里输出定码率（CBR），优点是体积可精确预估、兼容性最好。VBR 在同等平均码率下音质通常更优，但部分老设备和流媒体系统对 VBR 支持不佳。" }, { question: "怎么算出需要哪个档位？", answer: "体积 ≈ 比特率 ÷ 8 × 秒数。例如 10 分钟音频要压到 10 MB 以内，10 × 1024 × 8 ÷ 600 ≈ 136 kbps，选 128 kbps 即可留出余量。" }],
    reference: [['kbps', 'kilobits per second，每秒数千比特的编码数据量单位。'], ['re-encoding', '解码已有文件后以新的编码设置再次生成音频。']],
  },
  en: {
    overview: ['Audio bitrate is the amount of encoded data used each second. In lossy formats such as MP3, a higher value generally retains more detail but produces a larger file; actual quality also depends on encoder, channels, source, and content complexity.', 'Changing bitrate requires re-encoding and cannot turn a low-rate source into high-fidelity audio. Use the tool to make delivery copies for platform limits, download speed, or storage budgets while retaining the original master.'],
    steps: [['Confirm source and constraints', 'Record source parameters and the target platform’s maximum size or recommended rate.'], ['Choose the target', 'Speech can be tested lower, while complex music needs a conservative reduction.'], ['Listen and compare size', 'Inspect critical passages and download size, choosing the version that meets the quality floor.']],
    scenarios: [['Standardizing delivery parameters', 'Output several spoken tracks at one bitrate for predictable platform handling and size.'], ['Reducing mobile transfer', 'Create a smaller copy for playback on constrained networks.'], ["Meeting a platform's upload specification", "Some podcast hosts and content systems state a required bitrate, and the file has to be re-encoded to that number to pass validation."]],
    notes: ['Converting 64 kbps to 320 kbps only enlarges the file and cannot restore detail.', 'The same number across different codecs does not imply the same quality.', 'Constant bitrate makes size predictable, while content-aware encoding efficiency varies by passage.'],
    specs: [["Available steps", "Commonly 96 / 128 / 192 / 256 / 320 kbps; pick what the target system asks for"], ["Encoding mode", "Constant bitrate (CBR), so the data per second is fixed and the size is predictable against an upload limit"], ["Raising the bitrate", "Does not improve quality, only size; information absent from the source cannot be reconstructed"], ["Duration and channels", "Unchanged; only the data rate differs"], ["Size arithmetic", "Size ≈ bitrate ÷ 8 × seconds, which you can invert to find the step that fits a limit"], ["Where it runs", "FFmpeg compiled to WebAssembly in your browser; the file is never uploaded"]],
    faq: [{ question: "Is there any point going from 128 to 320 kbps?", answer: "Only if a downstream system insists on 320. Quality does not improve; high frequencies already discarded do not return because more bits were allocated. You simply get a larger file." }, { question: "CBR or VBR?", answer: "Output here is constant bitrate, which makes size exactly predictable and is the most compatible. VBR usually sounds better at the same average rate, but some older devices and streaming systems handle it poorly." }, { question: "How do I work out which step I need?", answer: "Size ≈ bitrate ÷ 8 × seconds. To fit ten minutes under 10 MB: 10 × 1024 × 8 ÷ 600 ≈ 136 kbps, so 128 kbps leaves comfortable headroom." }],
    reference: [['kbps', 'Kilobits per second, a unit of thousands of encoded bits used each second.'], ['re-encoding', 'Decoding an existing file and generating audio again with new encoding settings.']],
  },
});
