import { defineToolContent } from './define';

export const audioSampleRateContent = defineToolContent({
  zh: {
    overview: ['采样率表示每秒记录多少个声音采样，常见值包括语音场景的 8、16、22.05 kHz，以及音乐和视频的 44.1、48 kHz。重采样把已有波形映射到新的采样网格，用于满足接口、设备或编辑项目的固定要求。', '提高采样率不会增加源文件中不存在的高频细节，只会生成更多样本；降低采样率则需要滤除超过新奈奎斯特频率的内容，否则会产生混叠。选择应以目标系统规范为准。'],
    steps: [['检查源与目标要求', '读取当前采样率，并确认语音模型、视频工程或设备需要的数值。'], ['选择目标采样率', '避免无目的地提高，降低时注意是否会损失所需高频。'], ['转换并验证', '试听清晰度并在接收软件中确认文件参数。']],
    scenarios: [['适配语音识别', '把录音统一为模型要求的 16 kHz 等输入规格。'], ['匹配视频工程', '将音频转换为常见 48 kHz，减少时间线自动重采样。'], ["为语音识别准备输入", "多数语音模型在 16 kHz 单声道上训练，把素材重采样到这个规格能减少不必要的计算，识别结果也更稳定。"]],
    notes: ['采样率与比特率不是同一参数，前者描述采样频率，后者描述每秒编码数据量。', '上采样不会提升真实音质，下采样会限制可表示的最高频率。', '多次重采样可能累积滤波误差，最好从原始文件一次转换。'],
    specs: [["常见目标值", "8 kHz（电话语音）、16 kHz（语音识别）、44.1 kHz（CD）、48 kHz（视频标准）"], ["降采样", "会丢掉高于新采样率一半的频率成分（奈奎斯特极限），不可逆"], ["升采样", "不增加信息量，只是按插值生成更多采样点，通常只为满足下游格式要求"], ["输出", "MP3。MP3 只支持有限的采样率集合，超出时会落到最接近的一档"], ["典型用途", "把素材对齐到语音识别模型或视频工程要求的采样率"], ["处理位置", "浏览器内的 FFmpeg WebAssembly，音频文件不上传"]],
    faq: [{ question: "降采样会损失什么？", answer: "会永久丢掉高于新采样率一半的所有频率成分。降到 16 kHz 后，8 kHz 以上的内容不复存在：对语音影响不大，对音乐是明显的劣化。" }, { question: "把 44.1 kHz 升到 48 kHz 有用吗？", answer: "不增加任何音质，只是插值出更多采样点。唯一的用途是满足下游要求，例如视频工程统一用 48 kHz。" }, { question: "采样率和比特率是一回事吗？", answer: "不是。采样率决定每秒采样多少次，影响可表示的频率上限；比特率决定每秒用多少数据存储，影响压缩程度。两者都会影响体积，但改变的是不同的东西。" }],
    reference: [['Nyquist frequency', '理论上可表示的最高频率，约为采样率的一半。'], ['resampling', '把一组离散音频采样转换到另一采样频率的过程。']],
  },
  en: {
    overview: ['Sample rate is the number of audio samples recorded each second. Common values include 8, 16, or 22.05 kHz for speech and 44.1 or 48 kHz for music and video. Resampling maps an existing waveform to a new grid for an API, device, or editing-project requirement.', 'Raising the rate does not add high-frequency detail absent from the source; it only creates more samples. Lowering it requires filtering above the new Nyquist frequency to avoid aliasing. Choose from the destination specification.'],
    steps: [['Check source and destination', 'Read the current rate and confirm what a speech model, video project, or device requires.'], ['Choose a target rate', 'Do not raise it without purpose, and consider needed high frequencies when lowering.'], ['Convert and validate', 'Listen for clarity and inspect file parameters in the receiving application.']],
    scenarios: [['Adapting to speech recognition', 'Standardize a recording to an input requirement such as 16 kHz.'], ['Matching a video project', 'Convert audio to common 48 kHz to reduce automatic timeline resampling.'], ["Preparing input for speech recognition", "Most speech models are trained on 16 kHz mono, so resampling to that spec cuts wasted computation and gives steadier results."]],
    notes: ['Sample rate and bitrate differ: one counts samples, while the other measures encoded data per second.', 'Upsampling does not improve real quality, and downsampling limits the highest representable frequency.', 'Repeated resampling can accumulate filtering errors; convert once from the source.'],
    specs: [["Common targets", "8 kHz (telephony), 16 kHz (speech recognition), 44.1 kHz (CD), 48 kHz (video standard)"], ["Downsampling", "Discards every frequency above half the new rate; the Nyquist limit; and cannot be undone"], ["Upsampling", "Adds no information; it interpolates extra samples, and is normally done only to satisfy a downstream format"], ["Output", "MP3, which supports a limited set of rates; anything outside it lands on the nearest supported rate"], ["Typical use", "Matching material to what a speech-recognition model or a video project requires"], ["Where it runs", "FFmpeg compiled to WebAssembly in your browser; the file is never uploaded"]],
    faq: [{ question: "What does downsampling cost me?", answer: "Every frequency above half the new rate is gone permanently. Drop to 16 kHz and nothing above 8 kHz survives; barely noticeable on speech, clearly damaging on music." }, { question: "Is there any point going from 44.1 to 48 kHz?", answer: "It adds no quality, only interpolated samples. The one reason to do it is a downstream requirement, such as a video project standardising on 48 kHz." }, { question: "Is sample rate the same as bitrate?", answer: "No. Sample rate is how many times per second the signal is measured and sets the highest representable frequency; bitrate is how much data per second is stored and sets the compression level. Both affect file size, but they change different things." }],
    reference: [['Nyquist frequency', 'The theoretical highest representable frequency, approximately half the sample rate.'], ['resampling', 'Converting discrete audio samples from one sampling frequency to another.']],
  },
});
