import { defineToolContent } from './define';

export const audioToWavContent = defineToolContent({
  zh: {
    overview: ['WAV 通常用未压缩 PCM 保存音频，文件较大但结构简单，适合编辑、分析和需要稳定兼容的中间文件。转换为 WAV 会把源文件解码成采样值，不会恢复 MP3、AAC 等有损来源中已经被舍弃的声音。', '工具在浏览器中生成 WAV，适合进入剪辑、转写或音频分析流程。输出体积由时长、采样率、位深和声道数共同决定，长录音可能显著占用内存和磁盘。'],
    steps: [['上传源音频', '确认时长和来源质量，并预估未压缩输出可能很大。'], ['执行 WAV 转换', '等待完整解码与编码，处理时保持页面打开。'], ['核对后使用', '试听开头与结尾，并在目标编辑器中确认采样率和声道。']],
    scenarios: [['准备编辑中间件', '把压缩音频转换为剪辑或信号处理软件易读取的 WAV。'], ['建立分析输入', '为波形检测、语音模型或兼容性较旧的系统提供 PCM 容器。'], ["交给不接受有损格式的流程", "部分音频分析工具、语音模型和母带处理链要求输入为未压缩 PCM，转成 WAV 才能进入下一步。"]],
    notes: ['WAV 体积大不等于音质得到提升，它只避免输出阶段继续使用有损压缩。', '超长或高采样率文件可能超过浏览器可用内存，应分段处理。', 'WAV 可以容纳不同编码，本工具输出的具体参数应以下载文件信息为准。'],
    specs: [["输入格式", "MP3、M4A / AAC、OGG、FLAC、WebM 等浏览器可解码的音频"], ["输出", "WAV（未压缩 PCM 容器），不做二次有损编码"], ["体积", "远大于源文件：44.1 kHz / 16 bit / 立体声约每分钟 10 MB"], ["能否恢复音质", "不能。从有损源转出的 WAV 只是把已损失的结果原样装进无损容器"], ["适用下游", "音频编辑软件、需要精确采样的处理链、不接受有损格式的场合"], ["处理位置", "浏览器内的 FFmpeg WebAssembly，音频文件不上传"]],
    faq: [{ question: "转成 WAV 能提升音质吗？", answer: "不能。WAV 只是无损容器，从 MP3 转来的 WAV 装的仍然是已经损失过的音频。它的价值在于后续处理不再叠加损失，而不是恢复。" }, { question: "为什么文件变得这么大？", answer: "WAV 不压缩。44.1 kHz、16 bit、立体声每分钟约 10 MB，是 128 kbps MP3 的十倍以上。这是无损存储的固有代价。" }, { question: "什么时候该用 WAV 而不是 MP3？", answer: "需要继续编辑、需要精确采样、或者下游明确不接受有损格式时用 WAV。只是听或者分享，MP3 在体积上优势明显。" }],
    reference: [['PCM', '按固定采样率记录声音振幅数值的常见数字音频表示。'], ['sample rate', '每秒记录的采样数量，例如 44.1 kHz 表示每秒 44,100 个采样。']],
  },
  en: {
    overview: ['WAV commonly stores uncompressed PCM. It is large but structurally simple and useful for editing, analysis, and reliable intermediate exchange. Converting to WAV decodes a source into samples and cannot restore sound discarded by lossy MP3 or AAC.', 'The browser-generated WAV can feed editing, transcription, or audio analysis. Size depends on duration, sample rate, bit depth, and channel count, so long recordings can consume substantial memory and storage.'],
    steps: [['Upload the source', 'Check duration and source quality and anticipate a much larger uncompressed output.'], ['Convert to WAV', 'Keep the page open while full decoding and encoding completes.'], ['Verify in the destination', 'Listen to the beginning and end and check sample rate and channels in the target editor.']],
    scenarios: [['Preparing an editing intermediate', 'Convert compressed audio into a WAV that editing or signal-processing software reads reliably.'], ['Creating an analysis input', 'Provide a PCM container to waveform tools, speech models, or older compatible systems.'], ["Feeding a pipeline that rejects lossy input", "Some analysis tools, speech models and mastering chains require uncompressed PCM, so WAV is the entry ticket."]],
    notes: ['A larger WAV does not improve source quality; it only avoids another lossy output stage.', 'Very long or high-rate files can exceed browser memory and should be handled in segments.', 'WAV can contain multiple encodings, so inspect the downloaded file for its exact parameters.'],
    specs: [["Input formats", "MP3, M4A / AAC, OGG, FLAC, WebM; anything the browser can decode"], ["Output", "WAV, an uncompressed PCM container, with no second lossy encode"], ["File size", "Far larger than the source: roughly 10 MB per minute at 44.1 kHz / 16-bit / stereo"], ["Can it restore quality", "No. WAV from a lossy source just packages the already-degraded result losslessly"], ["Good downstream for", "Audio editors, processing chains that need exact samples, anywhere lossy input is rejected"], ["Where it runs", "FFmpeg compiled to WebAssembly in your browser; the file is never uploaded"]],
    faq: [{ question: "Does converting to WAV improve quality?", answer: "No. WAV is just a lossless container, and WAV made from an MP3 still holds already-degraded audio. Its value is that later processing adds no further loss, not that anything is recovered." }, { question: "Why is the file so large?", answer: "WAV is uncompressed. At 44.1 kHz / 16-bit / stereo it runs about 10 MB per minute, more than ten times a 128 kbps MP3. That is the inherent cost of lossless storage." }, { question: "When should I choose WAV over MP3?", answer: "When you will keep editing, when exact samples matter, or when something downstream refuses lossy input. For listening and sharing, MP3's size advantage is decisive." }],
    reference: [['PCM', 'A common digital representation recording amplitude values at a fixed sampling rate.'], ['sample rate', 'Samples recorded per second, such as 44.1 kHz meaning 44,100 samples each second.']],
  },
});
