import { defineToolContent } from './define';

export const audioToTextContent = defineToolContent({
  zh: {
    overview: ['音频转文字使用语音识别模型把录音生成可编辑文本，支持文件转写和按界面能力进行实时录音识别。它适合会议、访谈、课程和语音备注的初稿整理，但不能保证逐字准确或区分所有说话者。', '口音、多人重叠、背景音乐、专业术语和低质量麦克风都会降低准确率。识别文本应与音频校对，尤其是姓名、数字、否定词和责任性表述，重要记录还需要人工确认时间和说话人。'],
    steps: [['选择清晰音频', '优先使用人声靠前、噪声较低且音量稳定的文件。'], ['启动转写', '上传文件或授权实时录音，等待模型处理和进度完成。'], ['校对并整理', '回听关键位置，修正专有名词、数字、标点和段落。']],
    scenarios: [['制作会议初稿', '快速获得可搜索文字，再由参会者校对结论与行动项。'], ['整理访谈资料', '把长录音转换为可检索内容，帮助定位主题和引用。'], ["为访谈录音生成初稿", "先自动转写出文字底稿，再人工校对，比从零听打节省大量时间。"]],
    notes: ['自动转写不应直接作为法律、医疗或财务事实的唯一记录。', '实时识别可能按时间片更新，网络、设备性能和浏览器权限会影响结果。', '处理他人声音和敏感会议时应取得授权并遵守数据保留规则。'],
    specs: [["模型", "浏览器内运行的开源 Whisper，首次使用需要下载数十 MB 模型文件"], ["语言", "支持多语种识别，中英文效果较好；口音重、术语密集的素材准确率下降明显"], ["耗时", "与音频长度和设备性能成正比，通常明显慢于实时播放，移动端可能无法完成长素材"], ["输出", "纯文本转写稿。断句由模型给出，不含说话人分离"], ["准确率边界", "背景音乐、多人重叠说话、远场录音会显著降低准确率，结果需要人工校对"], ["处理位置", "模型从网络下载，音频本身在浏览器内推理，不上传"]],
    faq: [{ question: "转写内容会被上传吗？", answer: "不会。模型文件从网络下载到浏览器，但推理在本地完成，音频本身不会离开你的设备。这也是它适合处理访谈、医疗记录这类敏感录音的原因。" }, { question: "为什么这么慢？", answer: "推理由你的设备完成，速度取决于 CPU 性能。通常明显慢于实时播放，一段 10 分钟的音频可能需要等待数分钟，手机上可能无法完成。" }, { question: "准确率能到多少？", answer: "清晰的单人朗读可以很高，但背景音乐、多人重叠说话、远场录音和专业术语都会显著拉低准确率。请把输出当作需要校对的初稿，而不是最终稿。" }],
    reference: [['speech recognition', '从声学信号推断词语和文本序列的过程。'], ['transcript', '音频内容的文字记录，自动生成版本通常需要人工校对。']],
  },
  en: {
    overview: ['Audio to text uses speech recognition to produce editable text from a file and, where supported by the interface, live microphone capture. It creates a first draft for meetings, interviews, lessons, and voice notes but cannot guarantee verbatim accuracy or identify every speaker.', 'Accents, overlapping speakers, music, specialist terms, and poor microphones reduce accuracy. Proofread against the audio, especially names, numbers, negations, and accountable statements, and manually confirm timing and speakers in important records.'],
    steps: [['Choose clear audio', 'Prefer a recording with forward speech, low noise, and stable volume.'], ['Start transcription', 'Upload a file or authorize live capture and wait for model processing to complete.'], ['Proofread and organize', 'Replay key locations and correct names, numbers, punctuation, and paragraph structure.']],
    scenarios: [['Drafting meeting notes', 'Create searchable text quickly, then have participants verify decisions and action items.'], ['Organizing an interview', 'Turn a long recording into searchable material for locating themes and quotations.'], ["Drafting a transcript from an interview", "Auto-transcribe first and proofread after; far quicker than typing from scratch while listening."]],
    notes: ['Automatic transcription must not be the sole legal, medical, or financial factual record.', 'Live recognition may update in timed segments and is affected by network, device performance, and browser permissions.', 'Obtain authorization and follow retention rules when handling other people’s voices or sensitive meetings.'],
    specs: [["Model", "Open-source Whisper running in-browser; the first run downloads tens of megabytes of model files"], ["Languages", "Multilingual, with solid results for English and Chinese; heavy accents and dense jargon reduce accuracy noticeably"], ["Time required", "Scales with audio length and device speed, and is usually well slower than real time; phones may not finish long material"], ["Output", "A plain-text transcript. Segmentation comes from the model, and there is no speaker separation"], ["Accuracy limits", "Background music, overlapping speakers and far-field recordings degrade it substantially; proofread the result"], ["Where it runs", "The model is downloaded, but inference on your audio happens in the browser and nothing is uploaded"]],
    faq: [{ question: "Is my audio uploaded?", answer: "No. The model files are downloaded to the browser, but inference happens locally and the audio never leaves your device. That is what makes it usable for interviews, medical notes and other sensitive recordings." }, { question: "Why is it so slow?", answer: "Inference runs on your device and speed follows your CPU. It is usually well slower than real time; ten minutes of audio can take several minutes to process, and phones may not finish at all." }, { question: "How accurate is it?", answer: "Very good on a single clear speaker, but background music, overlapping voices, far-field recording and specialist terminology all pull it down sharply. Treat the output as a draft to proofread, not a finished transcript." }],
    reference: [['speech recognition', 'The process of inferring words and text sequences from an acoustic signal.'], ['transcript', 'A written record of audio content; an automatically generated version normally needs proofreading.']],
  },
});
