import { defineToolContent } from './define';

export const audioTtsContent = defineToolContent({
  zh: {
    overview: ['文字转语音调用浏览器和操作系统提供的语音合成能力朗读输入内容，可选择当前设备可用的声音，并调整语速、音高和音量。声音列表与自然度因浏览器、系统语言包和设备而异，同一设置在另一台设备上可能得到不同结果。', '它适合无障碍试听、发音检查和原型旁白。合成语音可能读错姓名、缩写、数字和多语言文本，正式发布前应完整听校，并确认所用声音的许可和平台政策允许目标用途。'],
    steps: [['输入适合朗读的文本', '补充标点并拆分过长段落，避免依赖视觉格式表达含义。'], ['选择声音和参数', '试听设备可用语音，小幅调整速度、音高和音量。'], ['完整播放检查', '核对姓名、数字、停顿和语气，再用于演示或辅助阅读。']],
    scenarios: [['检查内容可听性', '听取页面文案或提示语，发现拗口句子和标点问题。'], ['制作原型旁白', '为交互演示和无障碍原型提供临时语音反馈。'], ["快速试听一段文案的口语效果", "把写好的旁白或提示语读一遍，判断长度和节奏是否合适，再决定要不要正式录制。"]],
    notes: ['语音由当前设备能力提供，网站无法保证所有用户看到相同声音。', '不要用合成语音冒充真实人物或制作未经授权的欺骗性内容。', '浏览器朗读不一定直接生成可下载音频，具体能力以页面控件为准。'],
    specs: [["合成引擎", "浏览器内置的 Web Speech API，实际音色由你的操作系统提供"], ["可用音色", "因系统而异：macOS、Windows、Android、iOS 各自的语音包不同，同一段文字在不同设备上听感不同"], ["语言支持", "取决于系统已安装的语音包，缺少对应语言时不会朗读或会用错误发音"], ["可调参数", "语速、音调和音量，取决于所选语音是否支持"], ["能否导出文件", "Web Speech API 只负责朗读，浏览器不提供直接导出音频文件的能力"], ["处理位置", "文字交给系统语音引擎处理，不发送到 ToolGarden 的服务器"]],
    faq: [{ question: "为什么我这里的声音和别人不一样？", answer: "音色由你的操作系统提供，不是这个页面自带的。macOS、Windows、Android 和 iOS 各有各的语音包，因此同一段文字在不同设备上听起来不同。" }, { question: "能把朗读结果保存成文件吗？", answer: "不能。浏览器的 Web Speech API 只负责朗读，没有提供导出音频的接口。需要音频文件请用录音笔录制系统输出，或使用专门的 TTS 服务。" }, { question: "为什么某种语言读不出来？", answer: "系统没有安装对应的语音包。可以在操作系统的语音或辅助功能设置里添加语言包，添加后刷新页面即可使用。" }],
    reference: [['speech synthesis', '把文本和语言规则转换成可播放语音的过程。'], ['voice', '由系统提供的语言、音色和发音实现。']],
  },
  en: {
    overview: ['Text to speech uses voices supplied by the browser and operating system to read input, with controls for an available voice, rate, pitch, and volume. Voice lists and naturalness vary by browser, installed language packs, and device, so identical settings can sound different elsewhere.', 'It suits accessibility preview, pronunciation checking, and prototype narration. Synthesis can misread names, abbreviations, numbers, and multilingual text, so listen through before publication and confirm that voice licensing and platform policy permit the intended use.'],
    steps: [['Enter speakable text', 'Add punctuation and split long paragraphs instead of relying on visual formatting for meaning.'], ['Choose voice and settings', 'Preview an available device voice and adjust rate, pitch, and volume modestly.'], ['Review the full reading', 'Verify names, numbers, pauses, and tone before using it in a demo or reading aid.']],
    scenarios: [['Checking how content sounds', 'Listen to page copy or prompts to find awkward sentences and punctuation problems.'], ['Creating prototype narration', 'Provide temporary spoken feedback for an interaction demo or accessibility prototype.'], ["Hearing how a script reads aloud", "Play back narration or a prompt to judge its length and rhythm before committing to a real recording."]],
    notes: ['Voices come from the current device, and the site cannot guarantee the same voice for every user.', 'Do not use synthetic speech to impersonate real people or create unauthorized deceptive material.', 'Browser playback does not necessarily create a downloadable audio file; follow the controls actually offered by the page.'],
    specs: [["Synthesis engine", "The browser's built-in Web Speech API, with the actual voices supplied by your operating system"], ["Available voices", "System-dependent: macOS, Windows, Android and iOS each ship different voice packs, so the same text sounds different across devices"], ["Language support", "Limited to the voice packs your system has installed; a missing language either will not speak or will be mispronounced"], ["Adjustable", "Rate, pitch and volume, to the extent the selected voice supports them"], ["Can it export a file", "No. The Web Speech API only speaks; browsers expose no way to save the synthesised audio directly"], ["Where it runs", "The text goes to your system's speech engine and is never sent to a ToolGarden server"]],
    faq: [{ question: "Why does it sound different on my machine?", answer: "The voices come from your operating system, not from this page. macOS, Windows, Android and iOS each ship their own voice packs, so identical text sounds different across devices." }, { question: "Can I save the speech as a file?", answer: "No. The browser's Web Speech API only speaks; it exposes no way to export the audio. For a file, record the system output with the Voice Recorder, or use a dedicated TTS service." }, { question: "Why will it not read a particular language?", answer: "That voice pack is not installed. Add the language in your operating system's speech or accessibility settings, then reload the page." }],
    reference: [['speech synthesis', 'Turning text and language rules into playable spoken audio.'], ['voice', 'A system-provided implementation of language, timbre, and pronunciation.']],
  },
});
