import { defineToolContent } from './define';

export const audioSplitStemsContent = defineToolContent({
  zh: {
    overview: ['音轨分离使用机器学习估计混合音频中的人声与伴奏等组成部分，并输出可单独试听的 stem。它并没有访问原始多轨工程，而是从最终混音反推，所以人声混响、同频乐器和立体声效果可能在多个结果中残留。', '首次运行通常需要加载模型，处理时间和内存随音频时长与设备性能增加。结果适合练习、草稿混音和内容分析，不应被当作录音棚原始分轨，也不能绕过音乐版权或演出权许可。'],
    steps: [['上传高质量混音', '优先使用无损或高比特率来源，避免从多次压缩文件开始。'], ['加载模型并分离', '保持页面打开，观察模型和处理进度。'], ['逐轨试听', '检查人声、鼓和伴奏残留，根据用途决定是否需要专业源轨。']],
    scenarios: [['制作练习伴奏', '降低或分离主唱，帮助排练旋律、和声或乐器段落。'], ['分析混音结构', '单独试听估计的人声和伴奏，理解编曲与频率重叠。'], ["为翻唱或练习准备伴奏", "把成品歌曲拆出伴奏轨用于跟唱练习，或单独取人声轨分析演唱细节。"]],
    notes: ['分离结果是估计值，强混响和频率重叠会产生水声、空洞或串轨。', '较长文件可能需要大量内存，出现性能问题时先裁短再处理。', '拥有分离文件不代表拥有复制、发布、改编或商业使用许可。'],
    specs: [["输出轨道", "人声、鼓、贝斯、吉他、钢琴和其他，共六条"], ["模型", "浏览器内运行的开源音源分离模型，首次使用需要下载模型文件"], ["耗时", "六条轨道需要完整推理，一首歌通常要等待数分钟，低配设备可能失败"], ["分离质量", "取决于混音。乐器界限清晰的编曲效果好，密集混音和重度压缩的母带会出现残留和串音"], ["不能做什么", "无法还原成录音时的原始分轨，输出是从成品混音中估计出来的近似结果"], ["处理位置", "模型从网络下载，音频本身在浏览器内推理，不上传"]],
    faq: [{ question: "分出来的轨道会有杂音吗？", answer: "多少都会有。分离是从成品混音里估计每个声源，编曲越密集、母带压缩越重，残留和串音就越明显。鼓和贝斯通常分得较干净，钢琴和吉他更容易互相干扰。" }, { question: "能拿到录音时的原始分轨吗？", answer: "不能。原始分轨只存在于制作方的工程文件里。这里输出的是从两声道混音反推出的近似结果，不是原始素材。" }, { question: "为什么处理时间这么长？", answer: "六条轨道需要完整的模型推理，计算量远大于普通格式转换。一首三四分钟的歌通常要等数分钟，低配设备可能中途失败。" }],
    reference: [['stem', '从完整混音中单独组织的一组声音，例如人声或伴奏。'], ['source separation', '从混合信号估计多个潜在声源的计算过程。']],
  },
  en: {
    overview: ['Stem separation uses machine learning to estimate components such as vocals and accompaniment from a mixed recording. It has no access to the original multitrack project and works backward from the final mix, so vocal reverb, instruments sharing frequencies, and stereo effects can remain across outputs.', 'The model usually loads on first use, and processing time and memory grow with duration and device limits. Results suit practice, draft remixes, and analysis, not studio source tracks, and they do not bypass music copyright or performance licensing.'],
    steps: [['Upload a strong source', 'Prefer lossless or high-bitrate audio rather than a file that has been repeatedly compressed.'], ['Load and separate', 'Keep the page open and monitor model and processing progress.'], ['Listen to each stem', 'Check vocal, drum, and accompaniment leakage and decide whether professional source tracks are required.']],
    scenarios: [['Creating practice accompaniment', 'Reduce or isolate a lead vocal to rehearse melody, harmony, or an instrument part.'], ['Analyzing a mix', 'Listen separately to estimated vocals and backing to understand arrangement and frequency overlap.'], ["Making a backing track to practise with", "Pull the instrumental out of a finished song to sing along to, or isolate the vocal to study the performance."]],
    notes: ['Output is an estimate, and heavy reverb or overlapping frequencies can create watery, hollow, or leaking artifacts.', 'Long files can require substantial memory; trim to a shorter section when performance is limited.', 'Possessing separated files does not grant rights to copy, publish, adapt, or use them commercially.'],
    specs: [["Output stems", "Six tracks: vocals, drums, bass, guitar, piano and other"], ["Model", "An open-source source-separation model running in-browser; the first run downloads the model files"], ["Time required", "All six stems need a full inference pass, so a song typically takes several minutes and can fail on low-end devices"], ["Separation quality", "Depends on the mix. Arrangements with clear instrument separation come out well; dense mixes and heavily compressed masters leave bleed and residue"], ["What it cannot do", "Recover the original multitrack recording; the output is an estimate derived from the finished mix"], ["Where it runs", "The model is downloaded, but inference on your audio happens in the browser and nothing is uploaded"]],
    faq: [{ question: "Will the stems have artefacts?", answer: "Always some. Separation estimates each source from a finished mix, and the denser the arrangement and heavier the mastering compression, the more residue and bleed you get. Drums and bass usually come out cleanest; piano and guitar interfere with each other most." }, { question: "Can I get the original studio multitrack?", answer: "No. Those exist only in the producer's session files. What you get here is an approximation inferred from the two-channel mix." }, { question: "Why does it take so long?", answer: "Six stems require a full model inference pass, which is far heavier than ordinary format conversion. A three- or four-minute song typically takes several minutes, and modest hardware may fail partway." }],
    reference: [['stem', 'A grouped audio component of a full mix, such as vocals or accompaniment.'], ['source separation', 'Computational estimation of multiple underlying sound sources from one mixed signal.']],
  },
});
