import { defineToolContent } from './define';

export const audioRemoveSilenceContent = defineToolContent({
  zh: {
    overview: ['静音移除会检测低于指定分贝阈值且持续达到设定时间的区间，并把这些区间从音频中删除。它能压缩会议停顿和语音备忘，但环境底噪、轻声词尾和自然呼吸可能与静音处于相近电平。', '阈值越高或最短持续时间越短，删除会越激进。处理后的时间轴会改变，原有字幕、章节和外部时间码将不再对齐；对话节奏也可能变得不自然，所以需要从保守设置开始。'],
    steps: [['试听噪声底与轻声', '找出安静环境声和最轻有效语音的大致电平差异。'], ['设置阈值与持续时间', '先用较低阈值和较长持续时间，只移除明显长停顿。'], ['通听连接点', '检查词尾、呼吸和句间节奏，必要时降低敏感度再导出。']],
    scenarios: [['压缩会议录音', '去掉长时间等待或无人发言段，缩短回听时间。'], ['整理语音笔记', '删除录制前后及思考中的长静音，保留主要口述内容。'], ["清理口述录音的停顿", "一段带大量思考停顿的口述稿，自动裁掉空白后时长可能缩短两三成，听感更紧凑。"]],
    notes: ['背景噪声较高时静音可能无法被检测，降噪和静音移除是不同处理。', '设置过激会截断轻声、词尾和音乐休止，应检查完整文件。', '删除区间后所有后续时间点都会前移，外部标注需要重新生成。'],
    specs: [["判定依据", "音量低于阈值且持续超过最小时长的片段会被裁掉"], ["阈值的影响", "阈值过高会误删气声和乐句尾音，过低则留不住效果；有环境底噪的录音需要调高"], ["不改变什么", "保留段落的音量、音高和顺序都不变，只是把空白删掉"], ["输出", "MP3。裁剪后重新编码，因此会有一次有损转换"], ["不适合的素材", "有持续背景音乐或环境声的录音：那里没有真正的「静音」可判定"], ["处理位置", "浏览器内的 FFmpeg WebAssembly，音频文件不上传"]],
    faq: [{ question: "阈值应该怎么设？", answer: "先用默认值跑一遍试听。如果气声和句尾被切掉，说明阈值太高需要调低；如果空白仍在，说明底噪高于阈值需要调高。安静环境录的音通常比嘈杂环境更容易设置。" }, { question: "会把说话内容误删吗？", answer: "可能。音量很轻的词句、气声和尾音都可能低于阈值。建议处理后完整听一遍，尤其确认每一句的开头和结尾是否完整。" }, { question: "有背景音乐的录音能用吗？", answer: "效果不好。持续的背景声意味着音量从未真正降到阈值以下，工具找不到可裁的段落。这类素材需要在音频编辑软件里手动处理。" }],
    reference: [['threshold dB', '把片段视为静音时使用的电平门限。'], ['minimum duration', '低于门限需要连续保持多久才会被删除。']],
  },
  en: {
    overview: ['Silence removal detects intervals below a chosen dB threshold for at least a selected duration and deletes them. It can shorten meeting pauses and voice memos, but room noise, quiet word endings, and natural breaths may sit near the same level as silence.', 'A higher threshold or shorter minimum duration removes more aggressively. The timeline changes, so subtitles, chapters, and external timecodes no longer align, and conversational rhythm may become unnatural. Begin conservatively.'],
    steps: [['Listen to noise and quiet speech', 'Estimate the level difference between room tone and the softest meaningful words.'], ['Set threshold and duration', 'Start with a lower threshold and longer duration to remove only obvious pauses.'], ['Review every join', 'Check word endings, breaths, and sentence rhythm, reducing sensitivity when needed.']],
    scenarios: [['Shortening a meeting recording', 'Remove extended waiting or no-speaker intervals to reduce review time.'], ['Cleaning a voice note', 'Delete long silence before, after, and between thoughts while retaining the spoken content.'], ["Tightening up dictation", "A dictated draft full of thinking pauses can lose twenty or thirty percent of its length once the gaps go, and listens far better for it."]],
    notes: ['High background noise can prevent silence detection; denoising and silence removal are separate operations.', 'Aggressive settings cut soft speech, word endings, and musical rests, so inspect the complete file.', 'Every later timestamp shifts after deletion, requiring external annotations to be regenerated.'],
    specs: [["Detection rule", "A stretch is cut when its level stays below the threshold for longer than the minimum duration"], ["Effect of the threshold", "Too high and you lose breaths and note tails; too low and nothing is removed. Recordings with room noise need it raised"], ["What stays the same", "Volume, pitch and order of the kept passages are untouched; only the gaps go"], ["Output", "MP3, re-encoded after trimming, so one lossy generation is added"], ["Poor candidates", "Recordings with continuous background music or room tone, where there is no true silence to detect"], ["Where it runs", "FFmpeg compiled to WebAssembly in your browser; the file is never uploaded"]],
    faq: [{ question: "How should I set the threshold?", answer: "Run it once at the default and listen. If breaths and sentence endings vanish, the threshold is too high; if the gaps remain, your noise floor sits above it and it needs raising. Recordings made in a quiet room are much easier to tune." }, { question: "Could it delete actual speech?", answer: "It can. Quietly spoken words, breaths and trailing syllables may all fall below the threshold. Listen to the whole result afterwards, paying attention to the start and end of every sentence." }, { question: "Does it work on recordings with background music?", answer: "Not well. Continuous background sound means the level never truly drops below the threshold, so there is nothing for the tool to find. That material needs manual editing in a DAW." }],
    reference: [['threshold dB', 'The level boundary below which a segment may be treated as silence.'], ['minimum duration', 'How long the signal must stay below the boundary before deletion.']],
  },
});
