import { defineToolContent } from './define';

export const audioCompressContent = defineToolContent({
  zh: {
    overview: ['音频压缩通过较低的有损编码比特率减少文件体积，便于上传、发送和网页加载。它不同于动态范围压缩，后者改变响亮与安静部分的差距；本工具主要改变编码数据量。', '可接受的设置取决于内容。单人语音通常比复杂音乐更能承受低比特率，背景噪声、混响和高频乐器则会消耗更多编码资源。应以实际试听为准，而不是只追求最小数字。'],
    steps: [['上传并记录原始体积', '确认来源音质和时长，避免从已经严重压缩的文件继续转码。'], ['选择目标比特率', '从满足体积要求的较高值开始，逐级降低比较。'], ['试听并比较', '重点检查齿音、金属感、立体声和安静段，再下载合适版本。']],
    scenarios: [['满足附件限制', '把录音压到邮件、表单或消息平台允许的体积。'], ['优化语音发布', '为播客预览、课程旁白或语音备注生成更小版本。'], ["把语音素材压到附件限制以内", "降低比特率可以明显缩小会议录音，但交付前仍要实际试听人声和背景噪声。"]],
    notes: ['降低比特率会永久舍弃声音信息，应保留高质量原件。', '文件大小还受时长和声道影响，同一比特率下双倍时长约需要双倍数据。', '动态范围压缩、响度标准化与编码压缩是不同处理。'],
    specs: [["压缩手段", "降低 MP3 比特率重新编码，不改变时长、采样率和声道"], ["典型效果", "320 kbps 降到 128 kbps 约省 60% 体积；语音是否适合更低档位需要结合源文件和实际试听判断"], ["不可逆", "有损重编码。已经丢掉的高频不会因为之后调高比特率而回来"], ["不适合的素材", "已经是低比特率的文件，继续压缩只会明显劣化而省不了多少"], ["与调整比特率的区别", "这里以「减小体积」为目标给出档位建议，调整比特率用于精确指定某个数值"], ["处理位置", "浏览器内的 FFmpeg WebAssembly，音频文件不上传"]],
    faq: [{ question: "压缩会不会让人听出来？", answer: "取决于素材、源文件和收听设备。语音通常比音乐更能承受较低比特率，但没有一个档位对所有内容都透明。请实际试听人声齿音、背景噪声和高频乐器，再决定是否保留结果。" }, { question: "压缩和调整比特率有什么不同？", answer: "底层是同一件事：重新编码到更低比特率。区别只在入口：这里围绕「把文件变小」给建议，调整比特率用于精确指定某个数值以满足格式要求。" }, { question: "压过一次还能再压吗？", answer: "技术上可以，但每一次都在已有损失上继续丢信息，劣化会明显累积。需要更小的文件时，请回到原始素材重新压一次，而不是压第二遍。" }],
    reference: [['codec compression', '利用声音感知模型减少表示数据量的编码过程。'], ['dynamic range', '音频中最安静与最响部分之间的电平范围。']],
  },
  en: {
    overview: ['Audio compression here reduces file size through a lower lossy encoding bitrate for uploads, messaging, and web delivery. It differs from dynamic-range compression, which changes the gap between loud and quiet passages; this tool primarily changes encoded data volume.', 'Acceptable settings depend on content. Solo speech usually tolerates lower bitrate than complex music, while background noise, reverberation, and high-frequency instruments consume more coding capacity. Judge by listening instead of pursuing the smallest number alone.'],
    steps: [['Upload and note source size', 'Check source quality and duration and avoid another generation from heavily compressed input when possible.'], ['Choose a target bitrate', 'Begin with the highest value that can meet the size need and step down for comparison.'], ['Listen and compare', 'Check sibilance, metallic artifacts, stereo image, and quiet passages before downloading.']],
    scenarios: [['Meeting an attachment limit', 'Reduce a recording to fit an email, form, or messaging platform.'], ['Optimizing spoken delivery', 'Create a smaller podcast preview, course narration, or voice-note version.'], ["Getting speech under an attachment limit", "A lower bitrate can reduce a meeting recording substantially, but the result still needs an actual listen before delivery."]],
    notes: ['Lower bitrate permanently discards sound information, so keep a high-quality original.', 'Size also depends on duration and channels; twice the duration needs roughly twice the data at one bitrate.', 'Dynamic-range compression, loudness normalization, and codec compression are separate processes.'],
    specs: [["How it compresses", "Re-encodes MP3 at a lower bitrate; duration, sample rate and channel count are unchanged"], ["Typical result", "320 kbps down to 128 kbps saves roughly 60%; whether speech suits a lower step depends on the source and an actual listening check"], ["Irreversible", "A lossy re-encode. High frequencies already discarded do not return if you raise the bitrate later"], ["Poor candidates", "Files that are already low-bitrate; compressing again degrades audibly for little saving"], ["vs Change Bitrate", "This one frames the choice around shrinking the file; Change Bitrate is for hitting an exact number"], ["Where it runs", "FFmpeg compiled to WebAssembly in your browser; the file is never uploaded"]],
    faq: [{ question: "Will anyone notice the compression?", answer: "It depends on the source, content, and listening equipment. Speech often tolerates a lower bitrate better than music, but no single setting is transparent for every file. Listen for vocal sibilance, background noise, and high-frequency instruments before keeping the result." }, { question: "How does this differ from Change Bitrate?", answer: "Underneath it is the same operation; re-encoding at a lower bitrate. Only the framing differs: this one is organised around making the file smaller, while Change Bitrate is for hitting an exact number a format demands." }, { question: "Can I compress an already-compressed file again?", answer: "Technically yes, but each pass discards information on top of what is already gone and the degradation stacks visibly. When you need it smaller, go back to the original and compress once, rather than compressing twice." }],
    reference: [['codec compression', 'An encoding process using perception to reduce the amount of data representing sound.'], ['dynamic range', 'The level difference between the quietest and loudest audio passages.']],
  },
});
