import { defineToolContent } from './define';

export const audioRecorderContent = defineToolContent({
  zh: {
    overview: ['浏览器录音器通过设备的麦克风权限采集声音，并使用浏览器支持的媒体格式保存录音。实际格式可能是 WebM、Ogg 或 M4A，取决于浏览器与系统；完成后还可按工具提供的流程转换为 MP3。', '录音质量更多取决于麦克风、距离、房间反射和输入电平。开始正式内容前应做短测试，佩戴耳机避免扬声器回授，并明确获得参与者同意及遵守当地录音法律。'],
    steps: [['授权并选择环境', '允许麦克风访问，在安静空间让麦克风与说话者保持稳定距离。'], ['进行短测试后录制', '检查电平、噪声和爆音，再开始完整录音。'], ['停止、试听并保存', '确认开头结尾完整，下载原始录音或按需要转换。']],
    scenarios: [['记录语音备忘', '快速保存口述想法、发音样例或问题说明。'], ['制作临时旁白', '为演示和原型录制一段可继续剪辑的解说。'], ["快速录一段语音备忘", "不想装应用时，打开页面即可录制并导出 MP3，录音只存在于浏览器内存中。"]],
    notes: ['浏览器只会在获得权限时访问麦克风，完成后仍应确认录音已经停止。', '不同浏览器支持的录音格式不一致，接收方若有要求应先做兼容测试。', '录制他人声音前需要取得同意，并遵守组织政策和适用法律。'],
    specs: [["权限", "需要浏览器麦克风授权。拒绝后无法录制，权限可在浏览器站点设置中改回"], ["录制来源", "系统当前的默认输入设备；插拔耳机或外置麦克风后可能需要重新开始"], ["输出", "MP3，录完可先试听再决定是否保存"], ["时长限制", "没有固定上限，实际受可用内存约束，长时间录制建议分段"], ["页面切换", "标签页被挂起或设备休眠会中断录制，长录音期间请保持页面在前台"], ["处理位置", "音频只存在于浏览器内存中，不上传，也不会自动保存"]],
    faq: [{ question: "录音会被上传吗？", answer: "不会。音频只存在于浏览器内存里，你不点保存就不会写到任何地方，页面也不会把它发送到服务器。" }, { question: "为什么点了录音没有声音？", answer: "常见原因有三个：浏览器麦克风权限被拒、系统选中的默认输入设备不是你以为的那个、或者系统层面对该浏览器禁用了麦克风。请依次检查这三处。" }, { question: "能录多长时间？", answer: "没有固定上限，实际受可用内存限制。长时间录制建议分段进行，中途切换标签页或设备休眠也会中断录制。" }],
    reference: [['MediaRecorder', '浏览器用于采集媒体流并生成录制数据的接口。'], ['input level', '进入录音系统的信号强度，过高会削波，过低会放大底噪。']],
  },
  en: {
    overview: ['The browser recorder captures sound after microphone permission and saves it with a media format supported by the browser. The actual result may be WebM, Ogg, or M4A depending on the browser and system, with an optional MP3 conversion workflow after recording.', 'Quality depends more on microphone, distance, room reflections, and input level. Make a short test before the real take, use headphones to prevent speaker feedback, and obtain participant consent while following applicable recording law.'],
    steps: [['Grant access and choose the environment', 'Allow microphone use and keep a stable distance in a quiet space.'], ['Test, then record', 'Check level, noise, and plosives before starting the complete take.'], ['Stop, review, and save', 'Confirm the beginning and end are complete, then download the source recording or convert as needed.']],
    scenarios: [['Capturing a voice memo', 'Quickly save a spoken idea, pronunciation sample, or issue description.'], ['Creating temporary narration', 'Record a voiceover for a presentation or prototype that can be edited later.'], ["Capturing a quick voice note", "When you would rather not install anything, open the page, record, and export an MP3; the audio never leaves browser memory."]],
    notes: ['The browser accesses the microphone only with permission; still confirm recording has stopped when finished.', 'Recording format support varies by browser, so test compatibility when a receiver has a fixed requirement.', 'Obtain consent before recording other people and follow organizational policy and applicable law.'],
    specs: [["Permission", "Requires microphone access in the browser. Denying it blocks recording; you can re-grant it in the site settings"], ["Input source", "Whatever the system currently has as the default input; plugging in headphones or a mic mid-session may require restarting"], ["Output", "MP3, with playback before you decide whether to save"], ["Length limit", "No fixed cap; available memory is the real constraint, so record long sessions in parts"], ["Switching tabs", "A suspended tab or a sleeping device interrupts the recording; keep the page in the foreground for long takes"], ["Where it runs", "Audio exists only in browser memory. It is not uploaded, and not auto-saved"]],
    faq: [{ question: "Is my recording uploaded?", answer: "No. The audio exists only in browser memory, nothing is written anywhere until you save it, and the page does not send it to a server." }, { question: "Why is there no sound when I record?", answer: "Three usual causes: the browser's microphone permission was denied, the system default input is not the device you assumed, or the OS has blocked microphone access for that browser. Check them in that order." }, { question: "How long can I record?", answer: "There is no fixed cap; available memory is the real limit. Record long sessions in parts, and note that switching tabs or letting the device sleep will interrupt the take." }],
    reference: [['MediaRecorder', 'A browser interface for capturing a media stream into recorded data.'], ['input level', 'Signal strength entering the recorder; too high clips, while too low exposes more noise.']],
  },
});
