import { defineToolContent } from './define';

export const pdfEncryptContent = defineToolContent({
  zh: {
    overview: ['PDF 加密会为文档设置打开密码和相应的加密保护，使没有密码的查看器无法直接读取内容。它适合在受控渠道中增加一层访问限制，但安全性取决于密码强度、所用算法、文件分发方式和接收方如何保存密码。', '密码保护不等于数字签名，也不能阻止已获得密码的人截图、复制页面或再次分发。敏感材料还应使用安全传输、最小权限、有效期和撤销机制，不要把文件与密码通过同一消息发送。'],
    steps: [['确认文件与接收人', '移除不必要的敏感页面，并明确谁需要访问。'], ['设置强而唯一的密码', '使用足够长的随机口令，不复用账户密码。'], ['验证并分开发送', '用新文件重新打开测试，再通过另一个可信渠道传递密码。']],
    scenarios: [['发送敏感附件', '为包含个人或商业信息的 PDF 增加打开密码。'], ['限制临时交付', '在没有更完整文档门户时，为小范围接收人提供基础访问控制。'], ["给要发出去的敏感文档加保护", "合同、报价单、体检报告在通过邮件或聊天工具发送前设置打开密码，密码另行通过其它渠道告知。"]],
    notes: ['忘记强密码后通常无法恢复文件，应在受控密码管理器中保存。', '权限限制在不同 PDF 查看器中的执行程度可能不同，不能作为强制防复制手段。', '加密不证明文件作者和完整性，真实性需要数字签名。'],
    specs: [["打开密码", "加密文档内容。没有密码无法读取页面，这是真正的保护"], ["权限限制", "禁止打印、复制等设置只是写给阅读器看的声明，取决于阅读器是否遵守，不是加密强度"], ["移除密码", "需要你知道现有密码。工具不做密码破解"], ["密码找回", "无法找回。忘记打开密码的文档在这里和在任何地方都打不开"], ["加密后的影响", "其它 PDF 工具（合并、拆分、加水印）在解密前都无法读取该文档"], ["处理位置", "浏览器内完成，文档和密码都不上传"]],
    faq: [{ question: "忘记密码能解开吗？", answer: "不能。这里不做密码破解，移除密码需要你知道现有密码。忘记打开密码的文档在任何合规工具里都打不开：这正是加密应有的效果。" }, { question: "禁止打印和禁止复制可靠吗？", answer: "不可靠。这类权限限制只是写在文档里的声明，取决于阅读器是否遵守，很多工具会直接忽略。真正需要保密请用打开密码，它是实际加密内容的。" }],
    reference: [['user password', '打开 PDF 时必须提供的口令。'], ['digital signature', '用于验证签署者和签署后文件是否改变的密码学机制，与加密用途不同。']],
  },
  en: {
    overview: ['PDF encryption sets an open password and cryptographic protection so a viewer cannot directly read the document without the password. It adds access friction in a controlled workflow, but security depends on password strength, algorithm, distribution, and how recipients store the secret.', 'Password protection is not a digital signature and cannot prevent an authorized reader from taking screenshots, copying pages, or redistributing content. Sensitive material also needs secure transfer, least privilege, expiry, and revocation. Do not send the file and password in one message.'],
    steps: [['Confirm the file and recipients', 'Remove unnecessary sensitive pages and identify exactly who needs access.'], ['Set a strong unique password', 'Use a long random passphrase that is not reused as an account password.'], ['Verify and send separately', 'Open the new file to test it, then share the password through another trusted channel.']],
    scenarios: [['Sending a sensitive attachment', 'Add an open password to a PDF containing personal or business information.'], ['Restricting a temporary delivery', 'Provide basic access control to a small group when a document portal is unavailable.'], ["Protecting a sensitive document before you send it", "Set an open password on a contract, quotation or medical report before it goes out by email or chat, and share the password through a different channel."]],
    notes: ['A strong forgotten password is generally unrecoverable, so store it in a controlled password manager.', 'Permission restrictions vary by PDF viewer and are not strong prevention against copying.', 'Encryption does not prove authorship or integrity; authenticity requires a digital signature.'],
    specs: [["Open password", "Encrypts the content. Without it the pages cannot be read at all; this is the real protection"], ["Permission flags", "No-printing and no-copying are declarations addressed to the reader application; they hold only if it honours them, and are not encryption strength"], ["Removing a password", "Requires knowing the current one. This is not a password cracker"], ["Password recovery", "Not possible. A document whose open password is forgotten cannot be opened here or anywhere else"], ["Knock-on effect", "Other PDF tools; merge, split, watermark; cannot read the document until it is decrypted"], ["Where it runs", "Entirely in the browser; neither the document nor the password is uploaded"]],
    faq: [{ question: "Can you open it if I forgot the password?", answer: "No. This is not a password cracker; removing a password requires knowing it. A document whose open password is lost cannot be opened by any legitimate tool; which is exactly what encryption is supposed to achieve." }, { question: "Are no-printing and no-copying reliable?", answer: "No. Those permission flags are declarations inside the document that depend on the reader honouring them, and plenty of tools simply ignore them. When something genuinely must stay private, use an open password, which actually encrypts the content." }],
    reference: [['user password', 'The secret required to open an encrypted PDF.'], ['digital signature', 'Cryptography verifying a signer and post-signing changes, serving a different purpose from encryption.']],
  },
});
