import { defineToolContent } from './define';

export const textMarkdownToPdfContent = defineToolContent({
  zh: {
    overview: ['Markdown 转 PDF 会先把轻量标记渲染成排版页面，再生成固定布局文档。标题、列表、引用、代码和表格会按当前样式输出，适合分享不希望继续编辑的说明、报告和笔记。', 'PDF 分页与网页流式布局不同，长代码块、宽表格、超大图片和孤行可能跨页不理想。相对资源路径、远程图片和特定平台扩展也不一定能加载，导出前应完整预览并调整 Markdown 结构。'],
    steps: [['输入或选择 Markdown 文件', '可以粘贴内容，也可以选择 .md 或 .markdown 文件；同时检查代码围栏、标题层级、表格和图片链接。'], ['预览分页效果', '关注宽内容、段落断页、中文字体和页边距。'], ['生成并打开 PDF', '搜索文字并逐页检查链接、图片、页码和代码格式。']],
    scenarios: [['发布技术说明', '把 README、操作指南或变更记录生成易分发 PDF。'], ['提交格式固定的报告', '用 Markdown 写作后输出不会因阅读器窗口改变的版本。'], ["把 README 转成可归档的文档", "项目说明和技术方案以 PDF 形式提交时，排版固定，接收方不需要 Markdown 渲染环境。"]],
    notes: ['不同 Markdown 方言支持的表格、任务列表和 HTML 功能可能不同。', '远程资源受网络和跨域限制，重要图片应确保在生成时可访问。', '生成 PDF 后仍应检查无障碍阅读顺序、标题结构和链接文本。'],
    specs: [["支持的语法", "标题、列表、表格、代码块、引用、链接、图片、加粗斜体等常见 Markdown"], ["分页", "自动分页，长表格和长代码块可能被跨页切断"], ["字体", "使用浏览器可获得的字体，中英文混排正常。不同系统的输出排版可能有细微差别"], ["图片", "远程图片需要可访问才能渲染；本地路径的图片无法加载"], ["不支持", "自定义 CSS、页眉页脚、页码模板、目录自动生成"], ["处理位置", "在浏览器内生成 PDF，Markdown 内容不上传"]],
    faq: [{ question: "长表格被切成两页怎么办？", answer: "自动分页无法感知表格的语义边界。可以在源 Markdown 里把大表拆成几个小表，或者减少列数、缩短单元格内容让表格整体变矮，从而落在同一页内。" }, { question: "为什么在别人电脑上打开排版不一样？", answer: "PDF 本身是固定版式，打开后不会变。如果不一样，说明是在对方机器上重新生成的：渲染依赖本机可用字体。请分发生成好的 PDF 文件本身，而不是让对方自己转换。" }],
    reference: [['Markdown renderer', '把标记语法解析为标题、段落和其它结构的程序。'], ['page break', '固定页面输出中从当前页切换到下一页的位置。']],
  },
  en: {
    overview: ['Markdown to PDF renders lightweight markup into styled pages and then a fixed-layout document. Headings, lists, quotations, code, and tables follow the current stylesheet, making guides, reports, and notes easy to distribute without continued editing.', 'PDF pagination differs from flowing web layout. Long code, wide tables, large images, and orphan lines can break poorly, while relative assets, remote images, and platform extensions may not load. Preview fully and adjust source structure before export.'],
    steps: [['Enter or choose a Markdown file', 'Paste content or choose a .md or .markdown file, then check code fences, heading hierarchy, tables, and image links.'], ['Preview pagination', 'Inspect wide content, paragraph breaks, non-Latin fonts, and margins.'], ['Generate and open the PDF', 'Search text and check links, images, page numbers, and code on every page.']],
    scenarios: [['Publishing technical instructions', 'Turn a README, procedure, or change log into a distributable PDF.'], ['Submitting a fixed report', 'Write in Markdown and output a version that does not reflow with the reader window.'], ["Turning a README into an archivable document", "Submitting project notes or a technical proposal as PDF fixes the layout and spares the recipient any Markdown tooling."]],
    notes: ['Markdown dialects differ in support for tables, task lists, and inline HTML.', 'Remote resources depend on network and cross-origin access, so ensure critical images load during generation.', 'Review accessibility reading order, heading structure, and link text in the generated PDF.'],
    specs: [["Supported syntax", "Headings, lists, tables, code blocks, blockquotes, links, images, bold and italic; the common Markdown set"], ["Pagination", "Automatic; long tables and long code blocks can be split across a page break"], ["Fonts", "Uses fonts available to the browser and handles mixed scripts. Output can differ slightly between operating systems"], ["Images", "Remote images must be reachable to render; local file paths cannot be loaded"], ["Not supported", "Custom CSS, headers and footers, page-number templates, automatic table of contents"], ["Where it runs", "The PDF is generated in the browser; your Markdown is never uploaded"]],
    faq: [{ question: "My long table is split across two pages.", answer: "Automatic pagination cannot see a table's semantic boundaries. Split the large table into smaller ones in the source Markdown, or reduce columns and shorten cell content so the whole table is short enough to fit on one page." }, { question: "Why does it look different on someone else's computer?", answer: "A PDF is a fixed layout and does not change once opened. If it differs, it was regenerated on their machine; rendering depends on locally available fonts. Distribute the generated PDF file itself rather than asking them to convert." }],
    reference: [['Markdown renderer', 'Software parsing markup syntax into headings, paragraphs, and other structures.'], ['page break', 'The point where fixed-page output moves from one page to the next.']],
  },
});
